### ISSUE TITLE
Duplicate _id

### ISSUE THREAD

**Issue by jaskinn** [peerlibrary/meteor-subscription-data#2]
```
Exception from sub company_metrics id ZRE5QKWMpdBLzxEBQ MinimongoError: Duplicate _id 'ZRE5QKWMpdBLzxEBQ'
 at MinimongoError (packages/minimongo/minimongo.js:44:1)
 at [object Object].LocalCollection.insert (packages/minimongo/minimongo.js:555:1)
 at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
 at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
 at [object Object].<anonymous> (packages/peerlibrary_subscription-data/packages/peerlibrary_subscription-data.js:145:1)
 at [object Object]._handler (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:342:1)
 at maybeAuditArgumentChecks (livedata_server.js:1698:12)
 at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
 at [object Object].subscriptionProto._runHandler (packages/meteorhacks_kadira/lib/hijack/wrap_subscription.js:12:1)
 at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
```

I'm seeing this quite a bit on production and I'm not sure how to proceed to figure out what is going wrong. Any suggestions?

**Comment by mitar** [comment]
I am not sure if this is a consequence of this package. It might be that it is something which happens inside reactive publish itself? Why do you think it is related to this package in particular?

**Comment by jaskinn** [comment]
I could not determine which package (out of subscription-data or reactive-publish) so I thought I would start with the one earliest in the trace.

I do suspect that this occurs when the user logs in multiple times (via web and mobile).

**Comment by mitar** [comment]
Is `ZRE5QKWMpdBLzxEBQ` an ID of a document in the database? Can you confirm this?

**Comment by mitar** [comment]
And how often does this happen to you? Regularly? Very occasionally?

**Comment by jaskinn** [comment]
That ID does not correspond to a document in the database.

I see this error regularly (6 times in the last hour).

**Comment by mitar** [comment]
Oh, you are right. This is coming from `SubscriptionData.insert` in this package. It seems `publish._subscriptionId` are not unique?

**Comment by mitar** [comment]
Can you show me `company_metrics` publish function? Or at least tell me if you are using `autorun` inside it?

**Comment by jaskinn** [comment]
I am using `autorun`

**Comment by mitar** [comment]
Is there any other exception which happens at the same time?

**Comment by jaskinn** [comment]
No.

I have just had the same error for two other subscriptions as well. One of them was the `users` subscription.

I'm not actually using the `subscription-data` package for these subscriptions.

**Comment by jaskinn** [comment]
```
Meteor.publish("units", function() {
    this.autorun(function(computation) {
        if (!this.userId) {
            // Must be logged in.
            this.ready();
            return
        }

        let user = Meteor.users.findOne({_id: this.userId})
        return Units.find({
            zId: {$in: user.profile.unitIds},
        })
    })
})
```

This is the subscription that also just had the same trace.

**Comment by jaskinn** [comment]
```
 Exception from sub units id u75e4rqWzTuXZnFCo MinimongoError: Duplicate _id 'u75e4rqWzTuXZnFCo'
 at MinimongoError (packages/minimongo/minimongo.js:44:1)
 at [object Object].LocalCollection.insert (packages/minimongo/minimongo.js:555:1)
 at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
 at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
 at [object Object].<anonymous> (packages/peerlibrary_subscription-data/packages/peerlibrary_subscription-data.js:145:1)
 at [object Object]._handler (packages/peerlibrary_reactive-publish/packages/peerlibrary_reactive-publish.js:342:1)
 at maybeAuditArgumentChecks (livedata_server.js:1698:12)
 at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
 at [object Object].subscriptionProto._runHandler (packages/meteorhacks_kadira/lib/hijack/wrap_subscription.js:12:1)
 at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
```

**Comment by mitar** [comment]
Thanks for reporting. I think I have enough information to at least start looking into this. I do not know when I will have time though.

**Comment by mitar** [comment]
I could not reproduce this or find a reason why would this be happening.

**Comment by mitar** [comment]
I made things a bit more robust, but I am not sure if it really helps. Please test.
