### ISSUE TITLE
TypeError: this.autorun is not a function

### ISSUE THREAD

**Issue by crapthings** [peerlibrary/meteor-subscription-data#6]
meteor 1.5.2.2

```
I20171009-15:04:22.318(8)? undefined
I20171009-15:04:22.542(8)? Exception from sub test1 id 5qAipkrmyKycTPxXL TypeError: this.autorun is not a function
I20171009-15:04:22.542(8)?     at [object Object].<anonymous> (server/main.js:21:8)
I20171009-15:04:22.543(8)?     at [object Object].newFunc [as _handler] (packages/peerlibrary_subscription-data/server.coffee:23:19)
I20171009-15:04:22.543(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171009-15:04:22.543(8)?     at packages/ddp-server/livedata_server.js:1043:15
I20171009-15:04:22.544(8)?     at [object Object].EVp.withValue (packages/meteor.js:1134:15)
I20171009-15:04:22.544(8)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20171009-15:04:22.544(8)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20171009-15:04:22.544(8)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20171009-15:04:22.545(8)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by crapthings** [comment]
```
I20171009-15:04:22.318(8)? undefined
I20171009-15:04:22.542(8)? Exception from sub test1 id 5qAipkrmyKycTPxXL TypeError: this.autorun is not a function
I20171009-15:04:22.542(8)?     at [object Object].<anonymous> (server/main.js:21:8)
I20171009-15:04:22.543(8)?     at [object Object].newFunc [as _handler] (packages/peerlibrary_subscription-data/server.coffee:23:19)
I20171009-15:04:22.543(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20171009-15:04:22.543(8)?     at packages/ddp-server/livedata_server.js:1043:15
I20171009-15:04:22.544(8)?     at [object Object].EVp.withValue (packages/meteor.js:1134:15)
I20171009-15:04:22.544(8)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20171009-15:04:22.544(8)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20171009-15:04:22.544(8)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20171009-15:04:22.545(8)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by crapthings** [comment]
tried 1.5.1  it doesn't work too

peerlibrary:assert@0.2.5
peerlibrary:check-extension@0.2.1
peerlibrary:computed-field@0.3.1
peerlibrary:data-lookup@0.1.0
peerlibrary:extend-publish@0.4.0
peerlibrary:subscription-data@0.6.0

**Comment by mitar** [comment]
`autorun` comes from [reactive-publish](https://github.com/peerlibrary/meteor-reactive-publish) package.

It is written in README:

> To be useful, use peerlibrary:reactive-publish and server-side autorun in your publish endpoint function to react to data context changes.

**Comment by crapthings** [comment]
oh sorry, didn't look readme carefully its 3 packages that should used all together
